sudo: false
language: node_js
cache:
  # yarn: true
  directories:
    - node_modules
node_js:
  - '9'
  - '8'
branches:
  only:
    - master
notifications:
  email: true
  webhooks:
    # urls:
    #  - 'https://www.travisbuddy.com/'
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: never
script:
  - npm run build
