sudo: required
language: node_js
dist: trusty
addons:
    chrome: stable
cache:
  # yarn: true
  directories:
    - node_modules
node_js:
  - '9'
  - '8'
branches:
  only:
    - master
notifications:
  email: true
  webhooks:
    # urls:
    #  - 'https://www.travisbuddy.com/'
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: never
before_script:
        - "sudo chown root /opt/google/chrome/chrome-sandbox"
        - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
script:
  - npm run test
